name: Unit Tests

on:
  push:
    branches:
      - main
      - feature

  pull_request:
    branches:
      - main
      - feature

jobs:
  unit-test:

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            cmake \
            ninja-build \
            build-essential \
            lcov

      - name: Configure CMake
        run: |
          cmake \
            -S tests \
            -B tests/build \
            -DENABLE_COVERAGE=ON

      - name: Build Tests
        run: |
          cmake --build tests/build

      - name: Run Google Tests
        run: |
          ./tests/build/PatientMonitorTests