name: Patient Monitor CI

on:
  push:
    branches:
      - main
      - feature

  pull_request:
    branches:
      - main
      - feature

jobs:
  unit-tests:

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            lcov

      - name: Configure CMake
        run: |
          cmake \
            -S tests \
            -B tests/build \
            -DENABLE_COVERAGE=ON

      - name: Build Unit Tests
        run: |
          cmake --build tests/build --parallel

      - name: Run Google Tests
        working-directory: tests/build
        run: |
          ./PatientMonitorTests

      - name: Generate Coverage Report
        working-directory: tests/build
        run: |
          make coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Coverage-Report
          path: tests/build/coverage